#!/usr/bin/env bash
# print domains and subdomains

# Function to display information about a specific subdomain
display_info() {
    domain="$1"
    subdomain="$2"
    record_type=$(dig +short -t A "$subdomain.$domain" | awk '{ print length($0) ? "A" : "CNAME" }')
    destination=$(dig +short "$subdomain.$domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main scriptch
main() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        # If only domain is provided, display information for default subdomains
        display_info "$domain" "www"
        display_info "$domain" "lb-01"
        display_info "$domain" "web-01"
        display_info "$domain" "web-02"
    else
        # If both domain and subdomain are provided, display information for the specified subdomain
        display_info "$domain" "$subdomain"
    fi
}

# Execute main function with provided arguments
main "$@"