#!/usr/bin/env bash
#install nginx and have a file that returns the string "Hello World!" inside it

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGU1wu4; }' /etc/nginx/sites-available/default

sudo nginx -t 

if sudo nginx -t; then
    sudo service nginx restart
else
    echo "Nginx configuration failed"
fi