#!/usr/bin/env bash
# Install nginx and configure a custom 404 error page

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \ \n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Ensure there's no duplication in redirections (the following line checks for existing redirections)
sudo sed -i '/redirect_me/d' /etc/nginx/sites-available/default

# Test the Nginx configuration for errors
sudo nginx -t

# Restart Nginx to apply changes if configuration is correct
if sudo nginx -t; then
    sudo service nginx restart
else
    echo "Nginx configuration failed"
fi
