#!/usr/bin/env bash
#fix issues from docker
#make apache server return Hello Holberton when querying root

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/ www/html/index.html
sudo /etc/init.d/apache2 restart
